<?php
if ($this->pageCount): ?>
    <div class="fg-toolbar tableFooter">
        <div class="dataTables_info" id="checkAll_info">
            <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
            of <?php echo $this->totalItemCount; ?>
        </div>


        <div class="dataTables_paginate paging_full_numbers" id="checkAll_paginate">
            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
                <a class="first paginate_button" tabindex="0" id="checkAll_first"
                   href="?page=<?php echo $this->first; ?>">First</a>
            <?php else: ?>
                <a class="first paginate_button paginate_button_disabled" tabindex="0" id="checkAll_first">First</a>
            <?php endif; ?>

            <!-- end First page link -->

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <a class="previous paginate_button" tabindex="0" id="checkAll_previous"
                   href="?page=<?php echo $this->previous; ?>">Previous</a>
            <?php else: ?>
                <a class="previous paginate_button paginate_button_disabled" tabindex="0" id="checkAll_previous">Previous</a>
            <?php endif; ?>
            <!-- end Previous page link -->

<span>
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page == $this->current) { ?>
        <a class="paginate_active" tabindex="0"><?php echo $page; ?></a>
    <?php } else { ?>
        <a class="paginate_button" tabindex="0" href="?page=<?php echo $page; ?>"><?php echo $page; ?></a>

    <?php } ?>
<?php endforeach; ?>
</span>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <a class="next paginate_button" tabindex="0" id="checkAll_next" href="?page=<?php echo $this->next; ?>">Next</a>
            <?php else: ?>
                <a class="next paginate_button paginate_button_disabled" tabindex="0" id="checkAll_next">Next</a>
            <?php endif; ?>
            <!-- end Next page link -->

            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <a class="last paginate_button" tabindex="0" id="checkAll_last" href="?page=<?php echo $this->last; ?>">Last</a>
            <?php else: ?>
                <a class="last paginate_button paginate_button_disabled" tabindex="0" id="checkAll_last">Last</a>
            <?php endif; ?>
            <!-- Last page link -->
        </div>

    </div>
<?php endif; ?>
<style>
    .dataTables_paginate {
        float: right;
        margin-top: 7px;
    }

    .dataTables_paginate .last {
        margin-right: 0 !important;
    }

    /* Two button pagination - previous / next */
    .paginate_disabled_previous, .paginate_enabled_previous, .paginate_disabled_next, .paginate_enabled_next {
        height: 19px;
        float: left;
        cursor: pointer;
        *cursor: hand;
        color: #111 !important;
    }

    .paginate_disabled_previous:hover, .paginate_enabled_previous:hover, .paginate_disabled_next:hover, .paginate_enabled_next:hover {
        text-decoration: none !important;
    }

    .paginate_disabled_previous:active, .paginate_enabled_previous:active, .paginate_disabled_next:active, .paginate_enabled_next:active {
        outline: none;
    }

    .paginate_disabled_previous, .paginate_disabled_next {
        color: #666 !important;
    }

    .paginate_disabled_previous, .paginate_enabled_previous {
        padding-left: 23px;
    }

    .paginate_disabled_next, .paginate_enabled_next {
        padding-right: 23px;
        margin-left: 10px;
    }

    .paginate_enabled_previous {
        background: url('../images/tables/back_enabled.png') no-repeat top left;
    }

    .paginate_enabled_previous:hover {
        background: url('../images/tables/back_enabled_hover.png') no-repeat top left;
    }

    .paginate_disabled_previous {
        background: url('../images/tables/back_disabled.png') no-repeat top left;
    }

    .paginate_enabled_next {
        background: url('../images/tables/forward_enabled.png') no-repeat top right;
    }

    .paginate_enabled_next:hover {
        background: url('../images/tables/forward_enabled_hover.png') no-repeat top right;
    }

    .paginate_disabled_next {
        background: url('../images/tables/forward_disabled.png') no-repeat top right;
    }

</style>
