<?php
// Displaying the docType which we have defined in _initDoctype method of Bootstrap class found in application/Bootstrap.php 
echo $this->doctype()
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->title; ?></title>
        <?php
        // This file css/app.global.css is inside public folder.
        $this->headLink()->appendStylesheet($this->baseURL('css/app.global.css'));
        echo $this->headLink();
        ?>
        <!-- Fonts -->
        <link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->baseURL(); ?>"><b>Zend Framework 1 CRUD EXAMPLE</b></a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->baseURL('ticket/create'); ?>"><button type="button" class="btn btn-success">Add Ticket</button></a></li>
                        <li><a href="<?php echo $this->baseURL('ticket/cvsexport'); ?>"><button type="button" class="btn btn-success">CVS export</button></a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <?php
                    // Newly added code for FlashMessenger start here
                    $flashMessage = $this->messages;
                    if (is_array($flashMessage) && count($flashMessage) >= 1) {
                        foreach ($flashMessage[0] as $key => $value) {
                            echo '<div class="alert alert-' . $key . '">
                                    ' . $value . '
                                  </div>';
                        }
                    }
                    // Newly added code for FlashMessenger end here
                    ?>

                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>

        <!-- Scripts -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
    </body>
</html>